### PR TITLE
Return promise all

### PR DESCRIPTION
**Pull request by ruprict**
We had an issue in an isopmorphic app where the first action returned in the array would fire, then the page would render, leaving the other actions in the array to fire on the client.  Wrapping all the actions in `Promise.all` (which will just execute non-promises) fixed it for us. I think this will make this more friendly to async actions?

Whaddya think?

### CODE REVIEW

**Comment by ashaffer** [comment]
Cool thx.  I had been meaning to do this myself but got sidetracked.  Definitely a good idea.  New version should be published now.

**Comment by matthewmueller** [comment]
fyi, this breaks on IE11

**Comment by ashaffer** [comment]
@matthewmueller Hmm...you're right.  

I think I lean towards just reverting it then, and saying this sort of thing is an external concern.  It doesn't seem right to require a polyfill for a library this small.

@ruprict Are there other possible solutions for your use case?

**Comment by ruprict** [comment]
Well, crap. Lemme do a small bit of investigation this morning. Sorry I didn't catch it. I'll get back with you today.

**Comment by ruprict** [comment]
[lameExcuse]
We didn't see an issue b/c we are loading other modules that load the polyfill (fetch).
[/lameExcuse]

Here are the options I see:
1. Revert this. 
2. Include the dependency for ES6Promise.polyfill
3. Have the middleware check for `Promise` and then act accordingly.
4. I fork and make `redux-multi-promise`.

In the #3 case, something like:

```
function multi(_ref) {
  var dispatch = _ref.dispatch;

  return function (next) {
    return function (action) {
      if (!Array.isArray(action)) return next(action);
      if (typeof Promise === 'undefined')  {
        return action.filter(Boolean).map(dispatch);
      }
      return Promise.all(action.filter(Boolean).map(function (p) {
        return dispatch(p);
      }));
    };
  };
}
```

Obviously, it's really ip to @ashaffer, as this is his library. If you revert it, I understand. Again, I apologize for not catching the IE thing.  

Thoughts?

**Comment by ashaffer** [comment]
@ruprict No worries, I didn't catch it either.  I use redux-multi primarily with [redux-effects](https://github.com/redux-effects/redux-effects) for my async actions, and redux-effects does the Promise.all'ing on arrays for me there.  To me, that seems like a slightly more logical place for it.  My reasoning being that someone using say, [redux-thunk](https://github.com/gaearon/redux-thunk) for async actions shouldn't have to include a promise polyfill to use redux-multi.

Another solution is just to do this:

``` javascript
applyMiddleware(promisify, multi)

function promisify (api) {
  return next => action => {
    const result = next(action)
    return Array.isArray(result) ? Promise.all(result) : result
  }
}
```

This is one of the great things about redux middleware, is that all of these features can be expressed orthogonally to one another.

Would that address your use case?

**Comment by ruprict** [comment]
@ashaffer It doesn't look like it. If I put that in, `next(action)` calling `multi` is returning an object? I messed with it for a bit, but couldn't make it work. Probably doing something stupid, but it's pretty easy for me to just make a middleware that does what I need. I appreciate the try, but you can revert this.

**Comment by ashaffer** [comment]
@ruprict Is it returning an object because you still have the promise.all in there?  `next` should just return the return value of the next middleware in your stack.

**Comment by ruprict** [comment]
I agree, and I basically reverted my change locally before I made `promisify`. Not sure what I am doing wrong. I have `console.log`s everywhere. The middleware stuff is odd, as I  can put a log statement right above and before `next(action)`, along with log statements in the `next` and they don't come out in the logs in order.  So:

```
log statement before next
log statement after next

log statement within next
```

Does redux do something to the middleware? Any idea of what I could be doing wrong?

**Comment by ashaffer** [comment]
Hmm do you mind pasting your code?  I can't really tell from the description.  `next` should literally be the redux-multi function directly if they are adjacent (with promisify coming first) in your middleware stack.

**Comment by ruprict** [comment]
reduxy stuff

```
export default function(client: ApiClient, data: mixed): any {
  var middleware = clientMiddleware(client), finalCreateStore;
  if (process.env.NODE_ENV === 'development') {
    let devTools = require('redux-devtools');
    finalCreateStore =
      compose(
        applyMiddleware(middleware, effects, fetch, cookie(), promisify, multi),
        devTools.devTools(),
        typeof window !== 'undefined' ?
          devTools.persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/)) :
          identity,
    )(createStore);
  } else {
    finalCreateStore = applyMiddleware(middleware, effects, fetch, cookie(), promisify, multi)(createStore);
  }

  return finalCreateStore(reducer, data);
}
```

promisify

```
export default function promisify(_ref) {
  return next => action => {
    Array.isArray(action) ?
      Promise.all(next(action)) :
      next(action);
  }
}
```

redux-multi

```
function multi(_ref) {
  var dispatch = _ref.dispatch;

  return function (next) {
    return function (action) {
      return Array.isArray(action) ? action.filter(Boolean).map(function (p) {
        return dispatch(p);
      }) : next(action);
    };
  };
}
```

The promises don't "wait" like they should, meaning, the data isn't being built on the server when I go this route.

**Comment by ashaffer** [comment]
Oh, ya.  You need to execute the array using redux-multi first:

``` javascript
const result = next(action)
return Array.isArray(result) ? Promise.all(result) : result
```

rather than:

``` javascript
Array.isArray(action) ?
  Promise.all(next(action)) :
  next(action);
```

**Comment by ruprict** [comment]
Yeah, I tried that. Above represents one of many iterations. I will try a few more...

**Comment by ashaffer** [comment]
You're also not returning the value in your example, btw.

**Comment by ruprict** [comment]
OK, I finally found my dumb. I was changing the middleware chain on the client only, not the server side middleware chain.  Sorry, all of this is new to me (node, react, redux, isomorphic apps, thinking...)

Looks like it's working.

**Comment by ashaffer** [comment]
Awesome, sweet.  I'm gonna revert the change then, just wanted to make sure there was a good solution available for everyone.

**Pull request merged**
